-- USER SQL
CREATE USER SPRINGUSER IDENTIFIED BY 1004 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS

-- ROLES
GRANT "RESOURCE" TO SPRINGUSER WITH ADMIN OPTION;
GRANT "CONNECT" TO SPRINGUSER WITH ADMIN OPTION;
ALTER USER SPRINGUSER DEFAULT ROLE "RESOURCE","CONNECT";

-- SYSTEM PRIVILEGES





